"""new fields in user model

Revision ID: 388dc033c77a
Revises: 40c85d1d7c8c
Create Date: 2019-11-23 22:25:51.363498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388dc033c77a'
down_revision = '40c85d1d7c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
